# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import pymdurs
from pymdurs import geometric
import typing
from typing import Self, TypeAlias
__all__ = [
    "PyWindConfig",
    "PyWindField",
    "WindConfig",
    "WindField",
]

WindConfig: TypeAlias = PyWindConfig
WindField: TypeAlias = PyWindField
@typing.final
class PyWindConfig:
    r"""
    WindConfig: reference speed, direction, height, resolution, profile type, optional roughness.
    
    Grid spacing for the 3D solver: solver_dx/solver_dy override raster pixel size; solver_dz overrides
    the vertical step. When solver_dz is None, resolution_m is used as the vertical spacing (dz).
    """
    @property
    def wind_speed_ref(self) -> builtins.float: ...
    @wind_speed_ref.setter
    def wind_speed_ref(self, value: builtins.float) -> None: ...
    @property
    def wind_direction(self) -> builtins.float: ...
    @wind_direction.setter
    def wind_direction(self, value: builtins.float) -> None: ...
    @property
    def z_ref(self) -> builtins.float: ...
    @z_ref.setter
    def z_ref(self, value: builtins.float) -> None: ...
    @property
    def resolution_m(self) -> builtins.float:
        r"""
        Nominal resolution [m]. Also the default vertical step (dz) for the solver when solver_dz is None.
        """
    @resolution_m.setter
    def resolution_m(self, value: builtins.float) -> None:
        r"""
        Nominal resolution [m]. Also the default vertical step (dz) for the solver when solver_dz is None.
        """
    @property
    def profile_type(self) -> builtins.str:
        r"""
        Vertical profile: "log", "power_law" (default), "urban".
        """
    @profile_type.setter
    def profile_type(self, value: builtins.str) -> None:
        r"""
        Vertical profile: "log", "power_law" (default), "urban".
        """
    @property
    def z0(self) -> typing.Optional[builtins.float]: ...
    @z0.setter
    def z0(self, value: typing.Optional[builtins.float]) -> None: ...
    @property
    def d(self) -> typing.Optional[builtins.float]: ...
    @d.setter
    def d(self, value: typing.Optional[builtins.float]) -> None: ...
    @property
    def hr(self) -> typing.Optional[builtins.float]: ...
    @hr.setter
    def hr(self, value: typing.Optional[builtins.float]) -> None: ...
    @property
    def lambda_f(self) -> typing.Optional[builtins.float]: ...
    @lambda_f.setter
    def lambda_f(self, value: typing.Optional[builtins.float]) -> None: ...
    @property
    def use_mass_consistent_solver(self) -> builtins.bool: ...
    @use_mass_consistent_solver.setter
    def use_mass_consistent_solver(self, value: builtins.bool) -> None: ...
    @property
    def solver_epsilon(self) -> builtins.float: ...
    @solver_epsilon.setter
    def solver_epsilon(self, value: builtins.float) -> None: ...
    @property
    def solver_max_iter(self) -> builtins.int: ...
    @solver_max_iter.setter
    def solver_max_iter(self, value: builtins.int) -> None: ...
    @property
    def output_height(self) -> builtins.float: ...
    @output_height.setter
    def output_height(self, value: builtins.float) -> None: ...
    @property
    def solver_dx(self) -> typing.Optional[builtins.float]:
        r"""
        Solver grid spacing [m]: x. If None, use raster pixel size.
        """
    @solver_dx.setter
    def solver_dx(self, value: typing.Optional[builtins.float]) -> None:
        r"""
        Solver grid spacing [m]: x. If None, use raster pixel size.
        """
    @property
    def solver_dy(self) -> typing.Optional[builtins.float]:
        r"""
        Solver grid spacing [m]: y. If None, use raster pixel size.
        """
    @solver_dy.setter
    def solver_dy(self, value: typing.Optional[builtins.float]) -> None:
        r"""
        Solver grid spacing [m]: y. If None, use raster pixel size.
        """
    @property
    def solver_dz(self) -> typing.Optional[builtins.float]:
        r"""
        Solver grid spacing [m]: z (vertical). If None, use resolution_m.
        """
    @solver_dz.setter
    def solver_dz(self, value: typing.Optional[builtins.float]) -> None:
        r"""
        Solver grid spacing [m]: z (vertical). If None, use resolution_m.
        """
    @property
    def save_rockle_zone(self) -> builtins.bool:
        r"""
        If true, write rockle_zone.tif with Röckle zone codes (0=Freestream, 1=Inside, 2=Upwind, 3=UpwindVortex, 4=Cavity, 5=Wake, etc.).
        """
    @save_rockle_zone.setter
    def save_rockle_zone(self, value: builtins.bool) -> None:
        r"""
        If true, write rockle_zone.tif with Röckle zone codes (0=Freestream, 1=Inside, 2=Upwind, 3=UpwindVortex, 4=Cavity, 5=Wake, etc.).
        """
    def __new__(cls, wind_speed_ref: builtins.float = 3.5, wind_direction: builtins.float = 225.0, z_ref: builtins.float = 10.0, resolution_m: builtins.float = 2.0, profile_type: builtins.str = 'power_law', z0: typing.Optional[builtins.float] = None, d: typing.Optional[builtins.float] = None, hr: typing.Optional[builtins.float] = None, lambda_f: typing.Optional[builtins.float] = None, use_mass_consistent_solver: builtins.bool = False, solver_epsilon: builtins.float = 0.0001, solver_max_iter: builtins.int = 5000, output_height: builtins.float = 2.0, solver_dx: typing.Optional[builtins.float] = None, solver_dy: typing.Optional[builtins.float] = None, solver_dz: typing.Optional[builtins.float] = None, save_rockle_zone: builtins.bool = False) -> PyWindConfig: ...

@typing.final
class PyWindField:
    r"""
    WindField: Röckle-based urban wind solver (outputs wind_speed.tif, wind_direction.tif; optionally rockle_zone.tif when save_rockle_zone=True).
    """
    @property
    def geo_core(self) -> pymdurs.GeoCore:
        r"""
        Get GeoCore instance
        """
    def __new__(cls, output_path: typing.Optional[builtins.str] = None) -> PyWindField: ...
    def set_bbox(self, min_x: builtins.float, min_y: builtins.float, max_x: builtins.float, max_y: builtins.float) -> None:
        r"""
        Set bounding box (min_x, min_y, max_x, max_y) in project CRS.
        """
    def run(self, config: PyWindConfig, dem_path: builtins.str, dsm_path: builtins.str, buildings: geometric.Building) -> tuple[str, str, str | None]:
        r"""
        Run wind field: requires DEM and DSM GeoTIFF paths and a BuildingCollection.
        Writes wind_speed.tif and wind_direction.tif to the output path; if save_rockle_zone is True, also writes rockle_zone.tif.
        Returns (wind_speed_path, wind_direction_path, rockle_zone_path). rockle_zone_path is None when save_rockle_zone is False.
        """

