# This file is automatically generated by pyo3_stub_gen
# Python helpers from pymdurs.geometric_helpers appended manually — keep on regen.
# ruff: noqa: E501, F401, F403, F405

import builtins
import pandas
import pymdurs
import typing
from typing import Self, TypeAlias
import geopandas
__all__ = [
    "Building",
    "Cadastre",
    "Cosia",
    "Dem",
    "DetectionUrbanTypes",
    "Iris",
    "LAYER_PROPERTIES",
    "Lcz",
    "Lidar",
    "Mnh",
    "Mns",
    "Mnt",
    "PyBuilding",
    "PyCadastre",
    "PyCosia",
    "PyDem",
    "PyIris",
    "PyLcz",
    "PyLidar",
    "PyMnh",
    "PyMns",
    "PyMnt",
    "PyRnb",
    "PyRoad",
    "PyVegetation",
    "PyWater",
    "Rnb",
    "Road",
    "TABLE_COLOR_COSIA",
    "Vegetation",
    "Water",
    "calculate_centroid",
    "calculate_circumscribed_circle_radius",
    "create_circle",
    "dxf_to_cosia_and_weighted_layers",
    "dxf_to_polygon_shp",
]

Building: TypeAlias = PyBuilding
Cadastre: TypeAlias = PyCadastre
Cosia: TypeAlias = PyCosia
Dem: TypeAlias = PyDem
Iris: TypeAlias = PyIris
Lcz: TypeAlias = PyLcz
Lidar: TypeAlias = PyLidar
Mnh: TypeAlias = PyMnh
Mns: TypeAlias = PyMns
Mnt: TypeAlias = PyMnt
Rnb: TypeAlias = PyRnb
Road: TypeAlias = PyRoad
Vegetation: TypeAlias = PyVegetation
Water: TypeAlias = PyWater
@typing.final
class PyBuilding:
    r"""
    BuildingCollection Python binding (exposed as Building to match Python API)
    """
    @property
    def geo_core(self) -> pymdurs.GeoCore:
        r"""
        Get GeoCore instance
        """
    def __new__(cls, filepath_shp: typing.Optional[builtins.str] = None, output_path: typing.Optional[builtins.str] = None, defaultStoreyHeight: builtins.float = 3.0, set_crs: typing.Optional[builtins.int] = None) -> PyBuilding: ...
    def set_bbox(self, min_x: builtins.float, min_y: builtins.float, max_x: builtins.float, max_y: builtins.float) -> None:
        r"""
        Set bounding box
        """
    def set_crs(self, epsg: builtins.int) -> None:
        r"""
        Set CRS
        """
    def run(self) -> Self:
        r"""
        Run processing: load data, process heights, return self
        """
    def __len__(self) -> builtins.int:
        r"""
        Get number of buildings
        """
    def to_pandas(self) -> pandas.DataFrame:
        r"""
        Convert to pandas DataFrame
        """
    @staticmethod
    def from_geojson(geojson_data: bytes, output_path: typing.Optional[builtins.str], default_storey_height: builtins.float, set_crs: typing.Optional[builtins.int]) -> PyBuilding:
        r"""
        Load from GeoJSON
        """
    @staticmethod
    def from_ign_api(output_path: typing.Optional[builtins.str], default_storey_height: builtins.float, bbox: typing.Optional[pymdurs.BoundingBox]) -> PyBuilding:
        r"""
        Load from IGN API
        """
    def get_geojson(self) -> dict[str, typing.Any]:
        r"""
        Get GeoJSON (equivalent to to_gdf() in Python)
        """

@typing.final
class PyCadastre:
    r"""
    Cadastre Python binding
    """
    @property
    def geo_core(self) -> pymdurs.GeoCore:
        r"""
        Get GeoCore instance
        """
    def __new__(cls, output_path: typing.Optional[builtins.str] = None) -> PyCadastre: ...
    def set_bbox(self, min_x: builtins.float, min_y: builtins.float, max_x: builtins.float, max_y: builtins.float) -> None:
        r"""
        Set bounding box
        """
    def set_crs(self, epsg: builtins.int) -> None:
        r"""
        Set CRS
        """
    def run(self) -> Self:
        r"""
        Run cadastre processing: download from IGN API, parse GeoJSON
        """
    def get_geojson(self) -> dict[str, typing.Any]:
        r"""
        Get GeoJSON (equivalent to to_gdf() in Python)
        """
    def to_geojson(self, name: typing.Optional[builtins.str] = None) -> None:
        r"""
        Save to GeoJSON file
        """
    def get_output_path(self) -> builtins.str:
        r"""
        Get output path
        """

@typing.final
class PyCosia:
    r"""
    Cosia Python binding
    """
    @property
    def geo_core(self) -> pymdurs.GeoCore:
        r"""
        Get GeoCore instance
        """
    def __new__(cls, output_path: typing.Optional[builtins.str] = None, template_raster_path: typing.Optional[builtins.str] = None) -> PyCosia: ...
    def set_bbox(self, min_x: builtins.float, min_y: builtins.float, max_x: builtins.float, max_y: builtins.float) -> None:
        r"""
        Set bounding box
        """
    def set_crs(self, epsg: builtins.int) -> None:
        r"""
        Set CRS
        """
    def run_ign(self) -> Self:
        r"""
        Run Cosia processing: download from IGN API
        """
    def get_path_save_tiff(self) -> builtins.str:
        r"""
        Get path to saved TIFF file
        """

@typing.final
class PyDem:
    r"""
    Dem Python binding
    """
    @property
    def geo_core(self) -> pymdurs.GeoCore:
        r"""
        Get GeoCore instance
        """
    def __new__(cls, output_path: typing.Optional[builtins.str] = None) -> PyDem: ...
    def set_bbox(self, min_x: builtins.float, min_y: builtins.float, max_x: builtins.float, max_y: builtins.float) -> None:
        r"""
        Set bounding box
        """
    def set_crs(self, epsg: builtins.int) -> None:
        r"""
        Set CRS
        """
    def run(self, shape: typing.Optional[tuple[builtins.int, builtins.int]] = None) -> Self:
        r"""
        Run DEM processing
        """
    def get_path_save_tiff(self) -> builtins.str:
        r"""
        Get path to saved TIFF file
        """
    def get_path_save_mask(self) -> builtins.str:
        r"""
        Get path to mask shapefile
        """

@typing.final
class PyIris:
    r"""
    Iris Python binding
    """
    @property
    def geo_core(self) -> pymdurs.GeoCore: ...
    def __new__(cls, output_path: typing.Optional[builtins.str] = None) -> PyIris: ...
    def set_bbox(self, min_x: builtins.float, min_y: builtins.float, max_x: builtins.float, max_y: builtins.float) -> None: ...
    def set_crs(self, epsg: builtins.int) -> None: ...
    def run(self) -> Self: ...
    def get_geojson(self) -> dict[str, typing.Any]: ...
    def to_geojson(self, name: typing.Optional[builtins.str] = None) -> None: ...
    def get_output_path(self) -> builtins.str: ...

@typing.final
class PyLcz:
    r"""
    Lcz Python binding
    """
    @property
    def geo_core(self) -> pymdurs.GeoCore: ...
    def __new__(cls, filepath_shp: typing.Optional[builtins.str] = None, output_path: typing.Optional[builtins.str] = None, set_crs: typing.Optional[builtins.int] = None) -> PyLcz: ...
    def set_bbox(self, min_x: builtins.float, min_y: builtins.float, max_x: builtins.float, max_y: builtins.float) -> None: ...
    def set_crs(self, epsg: builtins.int) -> None:
        r"""
        Set CRS
        """
    def run(self, zipfile_url: typing.Optional[builtins.str] = None) -> Self: ...
    def geojson(self) -> dict[str, typing.Any] | None: ...
    def to_geojson(self, name: typing.Optional[builtins.str] = None) -> None: ...
    def get_output_path(self) -> builtins.str: ...
    def get_table_color(self) -> dict[int, dict[str, str]]: ...

@typing.final
class PyLidar:
    r"""
    Lidar Python binding.
    Download and process LiDAR point clouds from IGN WFS; produces DSM, DTM, CHM GeoTIFFs.
    LAZ files are cached under output_path/.cache/laz to avoid re-downloading.
    """
    @property
    def geo_core(self) -> pymdurs.GeoCore:
        r"""
        GeoCore instance (bbox, epsg, output_path).
        """
    def __new__(cls, output_path: typing.Optional[builtins.str] = None, classification: typing.Optional[builtins.int] = None, bbox: typing.Optional[tuple[builtins.float, builtins.float, builtins.float, builtins.float]] = None) -> PyLidar:
        r"""
        Create a Lidar instance.
        
        Args:
            output_path: Directory for output GeoTIFFs and LAZ cache (default: temp).
            classification: Optional default classification filter.
            bbox: Optional (min_x, min_y, max_x, max_y) in WGS84; if set, fetches LAZ URLs immediately.
        """
    def set_bbox(self, min_x: builtins.float, min_y: builtins.float, max_x: builtins.float, max_y: builtins.float) -> None:
        r"""
        Set bounding box (WGS84) and fetch LAZ URLs from IGN WFS, then load points.
        Call this before run() if bbox was not passed to the constructor.
        """
    def set_classification(self, classification: typing.Optional[builtins.int]) -> None:
        r"""
        Set classification filter (optional).
        """
    def set_crs(self, epsg: builtins.int) -> None:
        r"""
        Set CRS (e.g. 2154 for Lambert-93). Default is 2154.
        """
    def run(self, file_name: typing.Optional[builtins.str] = None, classification_list: typing.Optional[typing.Sequence[builtins.int]] = None, resolution: typing.Optional[builtins.float] = None, write_out_file: builtins.bool = True) -> builtins.str:
        r"""
        Run LiDAR processing: build DSM/DTM/CHM from loaded points and save GeoTIFF.
        
        Args:
            file_name: Output filename (e.g. "DSM.tif", "CDSM.tif"). Default "lidar_cdsm.tif".
            classification_list: Point classes to include (e.g. [2,6,9] for ground+buildings, [3,4,5] for vegetation).
            resolution: Pixel size in metres. Default 1.0.
            write_out_file: If True, write GeoTIFF to disk.
        
        Returns:
            Path to the created GeoTIFF (3 bands: DSM, DTM, CHM).
        """
    def get_output_path(self) -> builtins.str:
        r"""
        Return the output directory path (string).
        """
    def list_copc_urls(self) -> typing.Sequence[builtins.str]:
        r"""
        COPC tile URLs intersecting the current bbox (after `set_bbox`).
        
        Returns URLs like:
        `https://data.geopf.fr/.../LHD_FXX_0399_6580_PTS_LAMB93_IGN69.copc.laz`
        """
    def list_laz_urls(self) -> typing.Sequence[builtins.str]:
        r"""
        All LAZ tile URLs (COPC and non-COPC) for the current bbox (after `set_bbox`).
        """
    def save(self, filename: builtins.str = 'bbox.las') -> builtins.str:
        r"""
        Export loaded LiDAR points (ROI of the current BBOX) to a LAS file.
        Uses points already loaded by set_bbox(). Use .las for uncompressed, .laz for compressed.
        
        Args:
            filename: Output path (e.g. "bbox.las"). If relative, saved under the Lidar output directory.
        
        Returns:
            Absolute path to the written file.
        """

@typing.final
class PyMnh:
    r"""
    MNH (LiDAR HD) Python binding
    """
    @property
    def geo_core(self) -> pymdurs.GeoCore: ...
    def __new__(cls, output_path: typing.Optional[builtins.str] = None) -> PyMnh: ...
    def set_bbox(self, min_x: builtins.float, min_y: builtins.float, max_x: builtins.float, max_y: builtins.float) -> None: ...
    def set_crs(self, epsg: builtins.int) -> None: ...
    def run(self) -> Self: ...
    def get_path_save_tiff(self) -> builtins.str: ...

@typing.final
class PyMns:
    r"""
    MNS (LiDAR HD) Python binding
    """
    @property
    def geo_core(self) -> pymdurs.GeoCore: ...
    def __new__(cls, output_path: typing.Optional[builtins.str] = None) -> PyMns: ...
    def set_bbox(self, min_x: builtins.float, min_y: builtins.float, max_x: builtins.float, max_y: builtins.float) -> None: ...
    def set_crs(self, epsg: builtins.int) -> None: ...
    def run(self) -> Self: ...
    def get_path_save_tiff(self) -> builtins.str: ...

@typing.final
class PyMnt:
    r"""
    MNT (LiDAR HD) Python binding
    """
    @property
    def geo_core(self) -> pymdurs.GeoCore: ...
    def __new__(cls, output_path: typing.Optional[builtins.str] = None) -> PyMnt: ...
    def set_bbox(self, min_x: builtins.float, min_y: builtins.float, max_x: builtins.float, max_y: builtins.float) -> None: ...
    def set_crs(self, epsg: builtins.int) -> None: ...
    def run(self) -> Self: ...
    def get_path_save_tiff(self) -> builtins.str: ...

@typing.final
class PyRnb:
    r"""
    RNB Python binding
    """
    @property
    def geo_core(self) -> pymdurs.GeoCore:
        r"""
        Get GeoCore instance
        """
    def __new__(cls, output_path: typing.Optional[builtins.str] = None) -> PyRnb: ...
    def set_bbox(self, min_x: builtins.float, min_y: builtins.float, max_x: builtins.float, max_y: builtins.float) -> None:
        r"""
        Set bounding box
        """
    def set_crs(self, epsg: builtins.int) -> None:
        r"""
        Set CRS
        """
    def run(self) -> Self:
        r"""
        Run RNB processing: fetch from RNB API, parse JSON, create GeoJSON
        """
    def get_geojson(self) -> dict[str, typing.Any]:
        r"""
        Get GeoJSON (equivalent to to_gdf() in Python)
        """
    def to_geojson(self, name: typing.Optional[builtins.str] = None) -> None:
        r"""
        Save to GPKG file
        """
    def get_output_path(self) -> builtins.str:
        r"""
        Get output path
        """

@typing.final
class PyRoad:
    r"""
    Road Python binding
    """
    @property
    def geo_core(self) -> pymdurs.GeoCore:
        r"""
        Get GeoCore instance
        """
    def __new__(cls, output_path: typing.Optional[builtins.str] = None) -> PyRoad: ...
    def set_bbox(self, min_x: builtins.float, min_y: builtins.float, max_x: builtins.float, max_y: builtins.float) -> None:
        r"""
        Set bounding box
        """
    def set_crs(self, epsg: builtins.int) -> None:
        r"""
        Set CRS
        """
    def run(self) -> Self:
        r"""
        Run road processing: download from IGN API, parse GeoJSON
        """
    def get_geojson(self) -> dict[str, typing.Any]:
        r"""
        Get GeoJSON (equivalent to to_gdf() in Python)
        """
    def to_geojson(self, name: typing.Optional[builtins.str] = None) -> None:
        r"""
        Save to GeoJSON file
        """
    def get_output_path(self) -> builtins.str:
        r"""
        Get output path
        """

@typing.final
class PyVegetation:
    r"""
    Vegetation Python binding
    """
    @property
    def geo_core(self) -> pymdurs.GeoCore:
        r"""
        Get GeoCore instance
        """
    @property
    def min_area(self) -> builtins.float:
        r"""
        Get minimum area filter
        """
    def __new__(cls, filepath_shp: typing.Optional[builtins.str] = None, output_path: typing.Optional[builtins.str] = None, set_crs: typing.Optional[builtins.int] = None, write_file: builtins.bool = False, min_area: builtins.float = 0.0) -> PyVegetation: ...
    def set_bbox(self, min_x: builtins.float, min_y: builtins.float, max_x: builtins.float, max_y: builtins.float) -> None:
        r"""
        Set bounding box
        """
    def set_crs(self, epsg: builtins.int) -> None:
        r"""
        Set CRS
        """
    def run(self) -> Self:
        r"""
        Run vegetation processing: calculate NDVI from IRC or load from shapefile
        """
    def get_geojson(self) -> dict[str, typing.Any]:
        r"""
        Get GeoJSON (equivalent to to_gdf() in Python)
        """
    def to_geojson(self, name: typing.Optional[builtins.str] = None) -> None:
        r"""
        Save to GeoJSON file
        """
    def get_output_path(self) -> builtins.str:
        r"""
        Get output path
        """

@typing.final
class PyWater:
    r"""
    Water Python binding
    """
    @property
    def geo_core(self) -> pymdurs.GeoCore:
        r"""
        Get GeoCore instance
        """
    def __new__(cls, filepath_shp: typing.Optional[builtins.str] = None, output_path: typing.Optional[builtins.str] = None, set_crs: typing.Optional[builtins.int] = None) -> PyWater: ...
    def set_bbox(self, min_x: builtins.float, min_y: builtins.float, max_x: builtins.float, max_y: builtins.float) -> None:
        r"""
        Set bounding box
        """
    def set_crs(self, epsg: builtins.int) -> None:
        r"""
        Set CRS
        """
    def run(self) -> Self:
        r"""
        Run water processing: download from IGN API or load from shapefile, parse GeoJSON
        """
    def get_geojson(self) -> dict[str, typing.Any]:
        r"""
        Get GeoJSON (equivalent to to_gdf() in Python)
        """
    def to_geojson(self, name: typing.Optional[builtins.str] = None) -> None:
        r"""
        Save to GeoJSON file
        """
    def get_output_path(self) -> builtins.str:
        r"""
        Get output path
        """

# --- Pure-Python geometric helpers (injected at runtime via pymdurs.__init__) ---

TABLE_COLOR_COSIA: dict[builtins.str, builtins.str]
LAYER_PROPERTIES: dict[builtins.str, dict[builtins.str, builtins.float | builtins.str]]

def create_circle(
    center: tuple[builtins.float, builtins.float],
    radius: builtins.float,
    num_segments: builtins.int = 36,
) -> typing.Any: ...

def calculate_centroid(geometry: typing.Any) -> tuple[builtins.float, builtins.float]: ...

def calculate_circumscribed_circle_radius(
    geometry: typing.Any,
) -> tuple[builtins.float, tuple[builtins.float, builtins.float]]: ...

def dxf_to_polygon_shp(
    input_dxf: builtins.str | typing.Any,
    output_shp: builtins.str | typing.Any,
    encoding: builtins.str = "UTF-8",
    crs: builtins.str = "EPSG:3946",
) -> geopandas.GeoDataFrame: ...

def dxf_to_cosia_and_weighted_layers(
    input_shp_dxf: builtins.str | typing.Any,
    output_shp_gdf: builtins.str | typing.Any,
    bbox_coords: typing.Optional[typing.Sequence[builtins.float]] = None,
    bbox_crs: builtins.str = "EPSG:4326",
    encoding: builtins.str = "UTF-8",
    layer_properties: typing.Optional[dict[builtins.str, dict[builtins.str, builtins.float | builtins.str]]] = None,
) -> geopandas.GeoDataFrame: ...

@typing.final
class DetectionUrbanTypes:
    r"""
    Cluster buildings into urban morphotypes (momepy + Clustergram).
    """
    output_path: builtins.str
    gdf: typing.Optional[geopandas.GeoDataFrame]
    def __init__(self, output_path: typing.Optional[builtins.str] = None) -> None: ...
    def set_bbox(
        self,
        min_x: builtins.float,
        min_y: builtins.float,
        max_x: builtins.float,
        max_y: builtins.float,
    ) -> None: ...
    def set_crs(self, epsg: builtins.int) -> None: ...
    @property
    def bbox(self) -> typing.Optional[list[builtins.float]]: ...
    @bbox.setter
    def bbox(self, value: list[builtins.float]) -> None: ...
    @property
    def epsg(self) -> builtins.int: ...
    @epsg.setter
    def epsg(self, value: builtins.int) -> None: ...
    def run(self, nbr_cluster: builtins.int = 4) -> Self: ...
    def to_gdf(self) -> geopandas.GeoDataFrame: ...
    def to_gpkg(self, name: builtins.str = "detection") -> builtins.str: ...

