# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
from typing import TypeAlias
from . import geometric
from . import thermal
__all__ = [
    "BoundingBox",
    "GeoCore",
    "PyBoundingBox",
    "PyGeoCore",
    "geometric",
    "thermal",
]

BoundingBox: TypeAlias = PyBoundingBox
GeoCore: TypeAlias = PyGeoCore
@typing.final
class PyBoundingBox:
    r"""
    BoundingBox Python binding
    """
    @property
    def min_x(self) -> builtins.float: ...
    @property
    def min_y(self) -> builtins.float: ...
    @property
    def max_x(self) -> builtins.float: ...
    @property
    def max_y(self) -> builtins.float: ...
    def __new__(cls, min_x: builtins.float, min_y: builtins.float, max_x: builtins.float, max_y: builtins.float) -> PyBoundingBox: ...
    def transform(self, from_epsg: builtins.int, to_epsg: builtins.int) -> PyBoundingBox:
        r"""
        Transform bounding box to another CRS
        """

@typing.final
class PyGeoCore:
    r"""
    GeoCore Python binding
    """
    @property
    def epsg(self) -> builtins.int: ...
    @epsg.setter
    def epsg(self, value: builtins.int) -> None: ...
    @property
    def bbox(self) -> typing.Optional[PyBoundingBox]: ...
    @bbox.setter
    def bbox(self, value: typing.Optional[PyBoundingBox]) -> None: ...
    @property
    def output_path(self) -> typing.Optional[builtins.str]: ...
    @output_path.setter
    def output_path(self, value: typing.Optional[builtins.str]) -> None: ...
    def __new__(cls, epsg: builtins.int = 2154) -> PyGeoCore: ...

